### ISSUE TITLE
If the prefix and rewrite are same,the tranfic counld not be go into the endpoint.

### ISSUE THREAD

**Issue by lsk569937453** [lsk569937453/Spire#46]
```
- listen_port: 8000
  service_config:
    server_type: Http
    routes:
    - matcher:
        prefix: /app
        prefix_rewrite: /app
      route_cluster:
        type: RandomRoute
        routes:
        - base_route:
            endpoint: http://window-analyzer-backend:3333/
```
if the source endpoint is http://window-analyzer-backend:3333/app/test,so we can not reach it by the http://silverwind:8000/app/test.
